---
title: CloudCMD

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  cloudcmd:
    output: true

defaults:
  - scope:
      path: '_cloudcmd'
    values:
      layout: bin
