---
title: SkyFall

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  skyfall:
    output: true

defaults:
  - scope:
      path: '_skyfall'
    values:
      layout: bin
